import type { ServiceProvider, Token } from "@circulo-ai/di";
import * as dependencies from "./dependencies";

const STARTUP_TOKENS: readonly Token[] = [
  dependencies.CreateWebServerBackupScheduleUseCaseToken,
  dependencies.UpdateWebServerBackupScheduleUseCaseToken,
  dependencies.TestDockerRegistryConnectionUseCaseToken,
  dependencies.TestS3DestinationConnectionUseCaseToken,
  dependencies.GetServerHistoricalMetricsUseCaseToken,
  dependencies.RotateResourceWebhookTokenUseCaseToken,
  dependencies.CreateNotificationChannelUseCaseToken,
  dependencies.DeleteNotificationChannelUseCaseToken,
  dependencies.GetResourceRoutingTargetsUseCaseToken,
  dependencies.GetServerMonitoringStatusUseCaseToken,
  dependencies.RetryNotificationDeliveryUseCaseToken,
  dependencies.UpdateNotificationChannelUseCaseToken,
  dependencies.UpdateMonitoringSettingsUseCaseToken,
  dependencies.NotificationDeliveryRepositoryToken,
  dependencies.GetNotificationChannelsUseCaseToken,
  dependencies.TestNotificationChannelUseCaseToken,
  dependencies.UpdateWebServerSettingsUseCaseToken,
  dependencies.NotificationChannelRepositoryToken,
  dependencies.MonitoringSettingsRepositoryToken,
  dependencies.GetResourceContainersUseCaseToken,
  dependencies.GetServerRuntimeStatsUseCaseToken,
  dependencies.WebServerSettingsRepositoryToken,
  dependencies.CreateBackupScheduleUseCaseToken,
  dependencies.CreateDockerRegistryUseCaseToken,
  dependencies.DeleteBackupScheduleUseCaseToken,
  dependencies.DeleteDockerRegistryUseCaseToken,
  dependencies.GetSwarmJoinCommandsUseCaseToken,
  dependencies.GetWebServerSettingsUseCaseToken,
  dependencies.PruneDockerResourcesUseCaseToken,
  dependencies.RotateSwarmJoinTokenUseCaseToken,
  dependencies.UpdateBackupScheduleUseCaseToken,
  dependencies.UpdateDockerRegistryUseCaseToken,
  dependencies.CreateS3DestinationUseCaseToken,
  dependencies.DeleteS3DestinationUseCaseToken,
  dependencies.DeliverNotificationUseCaseToken,
  dependencies.GetDockerRegistriesUseCaseToken,
  dependencies.GetResourcePreviewsUseCaseToken,
  dependencies.ListComposeServicesUseCaseToken,
  dependencies.ListGitRepositoriesUseCaseToken,
  dependencies.PublishNotificationUseCaseToken,
  dependencies.UpdateS3DestinationUseCaseToken,
  dependencies.GetBackupSchedulesUseCaseToken,
  dependencies.GetDockerInventoryUseCaseToken,
  dependencies.GetSwarmContainersUseCaseToken,
  dependencies.BackupScheduleRepositoryToken,
  dependencies.AssignResourceTagUseCaseToken,
  dependencies.CreateCertificateUseCaseToken,
  dependencies.CreateEnvironmentUseCaseToken,
  dependencies.CreateGitProviderUseCaseToken,
  dependencies.DeleteCertificateUseCaseToken,
  dependencies.DeleteEnvironmentUseCaseToken,
  dependencies.DeleteGitProviderUseCaseToken,
  dependencies.GetS3DestinationsUseCaseToken,
  dependencies.ListBackupVolumesUseCaseToken,
  dependencies.RemoveResourceTagUseCaseToken,
  dependencies.UpdateCertificateUseCaseToken,
  dependencies.UpdateConcurrencyUseCaseToken,
  dependencies.UpdateGitProviderUseCaseToken,
  dependencies.S3DestinationRepositoryToken,
  dependencies.ControlContainerUseCaseToken,
  dependencies.DuplicateProjectUseCaseToken,
  dependencies.ExecuteBackupRunUseCaseToken,
  dependencies.GetAccountStatusUseCaseToken,
  dependencies.GetResourceStatsUseCaseToken,
  dependencies.GetWebServerLogsUseCaseToken,
  dependencies.ListCertificatesUseCaseToken,
  dependencies.ListResourceTagsUseCaseToken,
  dependencies.RandomizeComposeUseCaseToken,
  dependencies.RestoreBackupRunUseCaseToken,
  dependencies.RollbackResourceUseCaseToken,
  dependencies.TriggerBackupRunUseCaseToken,
  dependencies.ControlResourceUseCaseToken,
  dependencies.DatabaseCommandUseCaseToken,
  dependencies.GetEnvironmentsUseCaseToken,
  dependencies.GetGitProvidersUseCaseToken,
  dependencies.GetResourceLogsUseCaseToken,
  dependencies.GetUpdateStatusUseCaseToken,
  dependencies.ListGitBranchesUseCaseToken,
  dependencies.RebuildDatabaseUseCaseToken,
  dependencies.ReloadWebServerUseCaseToken,
  dependencies.RemoveSwarmNodeUseCaseToken,
  dependencies.UpdateSwarmNodeUseCaseToken,
  dependencies.CertificateRepositoryToken,
  dependencies.EnvironmentRepositoryToken,
  dependencies.GitProviderRepositoryToken,
  dependencies.CreateAuditLogUseCaseToken,
  dependencies.CreateResourceUseCaseToken,
  dependencies.CreateScheduleUseCaseToken,
  dependencies.CreateTemplateUseCaseToken,
  dependencies.DeleteResourceUseCaseToken,
  dependencies.DeleteScheduleUseCaseToken,
  dependencies.DeleteTemplateUseCaseToken,
  dependencies.DeployResourceUseCaseToken,
  dependencies.DeployTemplateUseCaseToken,
  dependencies.DockerReadOnlyServiceToken,
  dependencies.GenerateSshKeyUseCaseToken,
  dependencies.GetDeploymentsUseCaseToken,
  dependencies.GetEnvironmentUseCaseToken,
  dependencies.GetServerCountUseCaseToken,
  dependencies.InspectComposeUseCaseToken,
  dependencies.NotificationTransportToken,
  dependencies.UpdateResourceUseCaseToken,
  dependencies.UpdateScheduleUseCaseToken,
  dependencies.UpdateTemplateUseCaseToken,
  dependencies.ValidateDomainUseCaseToken,
  dependencies.CreateProjectUseCaseToken,
  dependencies.DeleteProjectUseCaseToken,
  dependencies.GetBackupRunsUseCaseToken,
  dependencies.GetSwarmNodesUseCaseToken,
  dependencies.ListAuditLogsUseCaseToken,
  dependencies.ListTemplatesUseCaseToken,
  dependencies.TriggerUpdateUseCaseToken,
  dependencies.BackupRunRepositoryToken,
  dependencies.CreateServerUseCaseToken,
  dependencies.CreateSshKeyUseCaseToken,
  dependencies.DeleteServerUseCaseToken,
  dependencies.DeleteSshKeyUseCaseToken,
  dependencies.GetResourcesUseCaseToken,
  dependencies.GetSchedulesUseCaseToken,
  dependencies.GetSwarmInfoUseCaseToken,
  dependencies.GlobalSearchUseCaseToken,
  dependencies.UpdateServerUseCaseToken,
  dependencies.UpdateSshKeyUseCaseToken,
  dependencies.ResourceRepositoryToken,
  dependencies.TemplateRepositoryToken,
  dependencies.GetProjectsUseCaseToken,
  dependencies.GetRequestsUseCaseToken,
  dependencies.GetResourceUseCaseToken,
  dependencies.SetupServerUseCaseToken,
  dependencies.ProjectRepositoryToken,
  dependencies.GetProjectUseCaseToken,
  dependencies.GetServersUseCaseToken,
  dependencies.GetSshKeysUseCaseToken,
  dependencies.SshKeyRepositoryToken,
  dependencies.CreateTagUseCaseToken,
  dependencies.DeleteTagUseCaseToken,
  dependencies.GeneralSchedulerToken,
  dependencies.GetServerUseCaseToken,
  dependencies.InitSwarmUseCaseToken,
  dependencies.UpdateTagUseCaseToken,
  dependencies.BackupSchedulerToken,
  dependencies.GetQueueUseCaseToken,
  dependencies.ListTagsUseCaseToken,
  dependencies.UserRepositoryToken,
  dependencies.TagRepositoryToken,
  dependencies.DockerServiceToken,
  dependencies.AIRepositoryToken,
  dependencies.CaddyServiceToken,
  dependencies.UnitOfWorkToken,
  dependencies.DbToken,
];

export function validateCompositionGraph(provider: ServiceProvider): void {
  const diagnostics = provider.validateGraph({ throwOnError: false });
  const errors = diagnostics.filter(
    (diagnostic) => diagnostic.level === "error",
  );
  if (errors.length > 0) {
    throw new Error(
      "Invalid dependency graph: " +
        errors.map((error) => error.message).join("\n"),
    );
  }

  const missing = STARTUP_TOKENS.filter((token) => !provider.has(token));
  if (missing.length > 0) {
    throw new Error(
      `Missing startup registrations: ${missing.map(String).join(", ")}`,
    );
  }
}
