version: 2

updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    reviewers:
      - mhbdev
    groups:
      bun-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    reviewers:
      - mhbdev
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    reviewers:
      - mhbdev
    groups:
      docker-images:
        patterns:
          - "*"

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    reviewers:
      - mhbdev
    groups:
      compose-images:
        patterns:
          - "*"
