/**
 * Application authorization is deliberately transport agnostic. Routers,
 * API keys, custom roles, and the Better Auth adapter consume this catalog
 * instead of maintaining their own lists of actions.
 */

export const AUTHORIZATION_SCOPES = [
  "instance",
  "organization",
  "project",
  "resource",
  "server",
] as const;

export type AuthorizationScope = (typeof AUTHORIZATION_SCOPES)[number];
export type OrganizationRole = "owner" | "admin" | "member";
export type AuthorizationAssurance = "standard" | "recent-2fa";

export type AuthorizationTarget =
  | { scope: "instance"; kind: "instance"; id?: string }
  | { scope: "organization"; kind: "organization"; organizationId: string }
  | { scope: "project"; kind: "project"; projectId: string }
  | { scope: "resource"; kind: "resource"; resourceId: string }
  | { scope: "server"; kind: "server"; serverId: string };

type CapabilityDefinition = {
  scope: AuthorizationScope;
  apiKey: boolean;
  customRole: boolean;
  assurance: AuthorizationAssurance;
  roles: readonly OrganizationRole[];
};

const ownerAdmin: readonly OrganizationRole[] = ["owner", "admin"];
const ownerAdminMember: readonly OrganizationRole[] = [
  "owner",
  "admin",
  "member",
];

/** The single source of truth for application capabilities. */
export const CAPABILITY_CATALOG = {
  "project:create": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "project:view": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdminMember,
  },
  "project:update": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "project:delete": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "recent-2fa",
    roles: ["owner"],
  },
  "tag:create": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "tag:view": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdminMember,
  },
  "tag:update": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "tag:delete": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "recent-2fa",
    roles: ownerAdmin,
  },
  "template:view": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdminMember,
  },
  "template:create": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "template:update": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "template:delete": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "recent-2fa",
    roles: ownerAdmin,
  },
  "template:deploy": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdminMember,
  },
  "environment:create": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "environment:view": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdminMember,
  },
  "environment:update": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "environment:delete": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "recent-2fa",
    roles: ownerAdmin,
  },
  "resource:create": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "resource:view": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdminMember,
  },
  "resource:update": {
    scope: "resource",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdminMember,
  },
  "resource:delete": {
    scope: "resource",
    apiKey: true,
    customRole: true,
    assurance: "recent-2fa",
    roles: ownerAdmin,
  },
  "ssh_key:create": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "ssh_key:update": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "ssh_key:view": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdminMember,
  },
  "ssh_key:delete": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "recent-2fa",
    roles: ownerAdmin,
  },
  "git_provider:create": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "git_provider:update": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "git_provider:view": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdminMember,
  },
  "git_provider:delete": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "recent-2fa",
    roles: ownerAdmin,
  },
  "s3_destination:create": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "s3_destination:view": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdminMember,
  },
  "s3_destination:update": {
    scope: "organization",
    apiKey: true,
    customRole: false,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "s3_destination:delete": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "recent-2fa",
    roles: ownerAdmin,
  },
  "backup:view": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdminMember,
  },
  "backup:manage": {
    scope: "resource",
    apiKey: true,
    customRole: true,
    assurance: "recent-2fa",
    roles: ownerAdmin,
  },
  "certificate:create": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "certificate:view": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdminMember,
  },
  "certificate:update": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "certificate:delete": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "recent-2fa",
    roles: ownerAdmin,
  },
  "docker_registry:create": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "docker_registry:update": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "docker_registry:view": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdminMember,
  },
  "docker_registry:delete": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "recent-2fa",
    roles: ownerAdmin,
  },
  "server:create": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "server:view": {
    scope: "server",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdminMember,
  },
  "server:update": {
    scope: "server",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "server:delete": {
    scope: "server",
    apiKey: true,
    customRole: true,
    assurance: "recent-2fa",
    roles: ownerAdmin,
  },
  "notification:create": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "notification:view": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdminMember,
  },
  "notification:update": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "notification:delete": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "recent-2fa",
    roles: ownerAdmin,
  },
  "audit_log:view": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "member:view": {
    scope: "organization",
    apiKey: false,
    customRole: false,
    assurance: "standard",
    roles: ownerAdminMember,
  },
  "member:manage": {
    scope: "organization",
    apiKey: false,
    customRole: false,
    assurance: "recent-2fa",
    roles: ownerAdmin,
  },
  "custom_role:view": {
    scope: "organization",
    apiKey: false,
    customRole: false,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "custom_role:manage": {
    scope: "organization",
    apiKey: false,
    customRole: false,
    assurance: "recent-2fa",
    roles: ownerAdmin,
  },
  "sso:view": {
    scope: "organization",
    apiKey: false,
    customRole: false,
    assurance: "standard",
    roles: ownerAdminMember,
  },
  "sso:manage": {
    scope: "organization",
    apiKey: false,
    customRole: false,
    assurance: "recent-2fa",
    roles: ownerAdmin,
  },
  "scim:view": {
    scope: "organization",
    apiKey: false,
    customRole: false,
    assurance: "standard",
    roles: ownerAdmin,
  },
  "scim:manage": {
    scope: "organization",
    apiKey: false,
    customRole: false,
    assurance: "recent-2fa",
    roles: ownerAdmin,
  },
  "api_key:manage": {
    scope: "organization",
    apiKey: false,
    customRole: false,
    assurance: "recent-2fa",
    roles: ownerAdmin,
  },
  "instance:manage": {
    scope: "instance",
    apiKey: false,
    customRole: false,
    assurance: "recent-2fa",
    roles: [],
  },
  // These capabilities are used by non-session integrations and are not
  // assignable to organization roles. They must not become instance grants.
  "deployment:view": {
    scope: "organization",
    apiKey: true,
    customRole: false,
    assurance: "standard",
    roles: [],
  },
  "deployment:manage": {
    scope: "resource",
    apiKey: true,
    customRole: false,
    assurance: "recent-2fa",
    roles: [],
  },
  "swarm:view": {
    scope: "organization",
    apiKey: true,
    customRole: false,
    assurance: "standard",
    roles: ["owner"],
  },
  "swarm:manage": {
    scope: "server",
    apiKey: true,
    customRole: false,
    assurance: "recent-2fa",
    roles: ["owner"],
  },
  "ai:view": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "standard",
    roles: ownerAdminMember,
  },
  "ai:manage": {
    scope: "organization",
    apiKey: true,
    customRole: true,
    assurance: "recent-2fa",
    roles: ownerAdmin,
  },
} as const satisfies Record<string, CapabilityDefinition>;

export type Capability = keyof typeof CAPABILITY_CATALOG;

export const CAPABILITY_ACTIONS = Object.keys(
  CAPABILITY_CATALOG,
) as Capability[];

export const API_KEY_CAPABILITY_ACTIONS = CAPABILITY_ACTIONS.filter(
  (capability) => CAPABILITY_CATALOG[capability].apiKey,
);

export const CUSTOM_ROLE_CAPABILITY_ACTIONS = CAPABILITY_ACTIONS.filter(
  (capability) => CAPABILITY_CATALOG[capability].customRole,
);

export function isCapability(value: string): value is Capability {
  return Object.hasOwn(CAPABILITY_CATALOG, value);
}

export function parseCapabilities(value: unknown): Capability[] {
  if (!Array.isArray(value)) return [];
  return [
    ...new Set(
      value.filter(
        (item): item is Capability =>
          typeof item === "string" && isCapability(item),
      ),
    ),
  ];
}

export function capabilitiesForRole(role: string): readonly Capability[] {
  if (role !== "owner" && role !== "admin" && role !== "member") return [];
  return CAPABILITY_ACTIONS.filter((capability) =>
    (
      CAPABILITY_CATALOG[capability].roles as readonly OrganizationRole[]
    ).includes(role),
  );
}

export function capabilityRequiresRecentTwoFactor(
  capability: Capability,
): boolean {
  return CAPABILITY_CATALOG[capability].assurance === "recent-2fa";
}

export const ORGANIZATION_STATEMENT = {
  organization: ["update", "delete"],
  member: ["create", "update", "delete"],
  invitation: ["create", "cancel"],
  team: ["create", "update", "delete"],
  ac: ["create", "read", "update", "delete"],
  apiKey: ["create", "read", "update", "delete"],
} as const;

export const ORGANIZATION_ROLE_STATEMENTS = {
  owner: {
    organization: ["update", "delete"],
    member: ["create", "update", "delete"],
    invitation: ["create", "cancel"],
    team: ["create", "update", "delete"],
    ac: ["create", "read", "update", "delete"],
    apiKey: ["create", "read", "update", "delete"],
  },
  admin: {
    organization: ["update"],
    member: ["create", "update", "delete"],
    invitation: ["create", "cancel"],
    team: ["create", "update", "delete"],
    ac: ["create", "read", "update", "delete"],
    apiKey: ["create", "read", "update", "delete"],
  },
  member: {
    organization: [],
    member: [],
    invitation: [],
    team: [],
    ac: ["read"],
    apiKey: [],
  },
} as const;

/**
 * API-key route declarations are validated against the same capability
 * catalog as session and custom-role checks.
 */
export const API_KEY_ROUTE_CAPABILITIES = {
  "application.get": "resource:view",
  "application.create": "resource:create",
  "application.update": "resource:update",
  "application.delete": "resource:delete",
  "compose.get": "resource:view",
  "compose.inspect": "resource:create",
  "compose.convert": "resource:create",
  "compose.create": "resource:create",
  "compose.update": "resource:update",
  "compose.deploy": "resource:update",
  "compose.control": "resource:update",
  "compose.delete": "resource:delete",
  "port.list": "resource:view",
  "port.create": "resource:update",
  "port.update": "resource:update",
  "port.delete": "resource:update",
  "mount.list": "resource:view",
  "mount.create": "resource:update",
  "mount.update": "resource:update",
  "mount.delete": "resource:update",
  "compose.randomize": "resource:update",
  "gitProvider.list": "git_provider:view",
  "gitProvider.create": "git_provider:create",
  "gitProvider.update": "git_provider:update",
  "gitProvider.delete": "git_provider:delete",
  "gitProvider.listRepositories": "git_provider:view",
  "gitProvider.listBranches": "git_provider:view",
  "database.get": "resource:view",
  "database.create": "resource:create",
  "database.update": "resource:update",
  "database.control": "resource:update",
  "database.rebuild": "resource:update",
  "database.command": "resource:update",
  "database.delete": "resource:delete",
  "domain.validate": "resource:view",
  "project.list": "project:view",
  "project.get": "project:view",
  "project.create": "project:create",
  "project.deleteProject": "project:delete",
  "environment.list": "environment:view",
  "environment.get": "environment:view",
  "environment.create": "environment:create",
  "environment.update": "environment:update",
  "environment.delete": "environment:delete",
  "resource.list": "resource:view",
  "resource.getContainers": "resource:view",
  "resource.getLogs": "resource:view",
  "resource.getStats": "resource:view",
  "resource.getRoutingTargets": "resource:view",
  "resource.create": "resource:create",
  "resource.update": "resource:update",
  "resource.deploy": "resource:update",
  "resource.control": "resource:update",
  "resource.rebuildDatabase": "resource:update",
  "resource.databaseCommand": "resource:update",
  "server.inventory": "server:view",
  "server.count": "server:view",
  "server.one": "server:view",
  "server.update": "server:update",
  "server.controlContainer": "server:update",
  "server.controlResource": "server:update",
  "server.validate": "server:view",
  "server.time": "server:view",
  "auditLog.list": "audit_log:view",
  "template.list": "template:view",
  "template.create": "template:create",
  "template.update": "template:update",
  "template.remove": "template:delete",
  "template.deploy": "template:deploy",
  "resource.randomizeCompose": "resource:update",
  "resource.getPreviews": "resource:view",
  "deployment.getServerSettings": "server:view",
  "deployment.getByResource": "deployment:view",
  "deployment.getDeployments": "deployment:view",
  "deployment.getQueue": "deployment:view",
  "deployment.getRequests": "deployment:view",
  "deployment.updateServerConcurrency": "server:update",
  "deployment.cancelDeploymentJob": "resource:update",
  "deployment.killBuild": "resource:update",
  "deployment.removeDeployment": "resource:update",
  "deployment.clearHistory": "resource:update",
  "resource.delete": "resource:delete",
  "resource.get": "resource:view",
  "resource.controlContainer": "resource:update",
  "resource.rotateWebhookToken": "resource:update",
  "resource.rollback": "resource:update",
  "dockerRegistry.list": "docker_registry:view",
  "dockerRegistry.create": "docker_registry:create",
  "dockerRegistry.update": "docker_registry:update",
  "dockerRegistry.delete": "docker_registry:delete",
  "dockerRegistry.testConnection": "docker_registry:view",
  "s3Destination.testConnection": "s3_destination:view",
  "s3Destination.list": "s3_destination:view",
  "s3Destination.create": "s3_destination:create",
  "s3Destination.update": "s3_destination:update",
  "s3Destination.delete": "s3_destination:delete",
  "schedule.list": "resource:view",
  "schedule.create": "resource:update",
  "schedule.update": "resource:update",
  "schedule.runNow": "resource:update",
  "schedule.delete": "resource:update",
  "schedule.listLogs": "resource:view",
  "schedule.listObservability": "resource:view",
  "backup.listSchedules": "backup:view",
  "backup.listRuns": "backup:view",
  "backup.listVolumes": "backup:view",
  "backup.listComposeServices": "backup:view",
  "backup.createSchedule": "backup:manage",
  "backup.updateSchedule": "backup:manage",
  "backup.deleteSchedule": "backup:manage",
  "backup.runNow": "backup:manage",
  "backup.restore": "backup:manage",
  "certificate.list": "certificate:view",
  "certificate.create": "certificate:create",
  "certificate.update": "certificate:update",
  "certificate.delete": "certificate:delete",
  "notification.list": "notification:view",
  "notification.create": "notification:create",
  "notification.update": "notification:update",
  "notification.remove": "notification:delete",
  "notification.test": "notification:update",
  "notification.deliveries": "notification:view",
  "notification.retryDelivery": "notification:update",
  "ai.listModels": "ai:manage",
  "ai.listProviders": "ai:view",
  "ai.listFeatureAssignments": "ai:view",
  "ai.conversations": "ai:view",
  "ai.getConversation": "ai:view",
  "ai.createConversation": "ai:view",
  "ai.addProvider": "ai:manage",
  "ai.updateProvider": "ai:manage",
  "ai.removeProvider": "ai:manage",
  "ai.testProvider": "ai:manage",
  "ai.saveFeatureAssignment": "ai:manage",
  "ai.removeFeatureAssignment": "ai:manage",
  "ai.deleteConversation": "ai:manage",
  "ai.generateTemplate": "ai:manage",
  "project.duplicate": "project:create",
  "project.update": "project:update",
  "template.catalog": "template:view",
  "search.global": "project:view",
  "server.create": "server:create",
  "server.delete": "server:delete",
  "server.list": "server:view",
  "server.historicalMetrics": "server:view",
  "server.monitoringSettings": "server:update",
  "server.monitoringStatus": "server:view",
  "server.runtimeStats": "server:view",
  "server.scanHostKey": "server:update",
  "server.setup": "server:update",
  "server.updateMonitoringSettings": "server:update",
  "sshKey.generate": "ssh_key:create",
  "sshKey.create": "ssh_key:create",
  "sshKey.list": "ssh_key:view",
  "sshKey.update": "ssh_key:update",
  "sshKey.delete": "ssh_key:delete",
  "tag.list": "tag:view",
  "tag.create": "tag:create",
  "tag.update": "tag:update",
  "tag.remove": "tag:delete",
  "tag.forResource": "tag:view",
  "tag.assign": "tag:update",
  "tag.removeFromResource": "tag:update",
} as const satisfies Record<string, Capability>;

export type ApiKeyRoute = keyof typeof API_KEY_ROUTE_CAPABILITIES;

/** Required application capability for every UpGal/MCP tool. */
export const MCP_TOOL_CAPABILITIES = {
  get_account_status: "project:view",
  list_templates: "template:view",
  get_template: "template:view",
  list_projects: "project:view",
  list_environments: "environment:view",
  list_resources: "resource:view",
  get_resource_logs: "resource:view",
  get_resource_stats: "resource:view",
  get_resource_config: "resource:view",
  list_servers: "server:view",
  get_monitoring_status: "server:view",
  get_monitoring_metrics: "server:view",
  list_deployments: "deployment:view",
  get_audit_logs: "audit_log:view",
  get_docker_info: "server:view",
  list_docker_containers: "server:view",
  list_docker_images: "server:view",
  list_docker_volumes: "server:view",
  list_docker_networks: "server:view",
  list_docker_services: "swarm:view",
  get_docker_logs: "server:view",
  create_project: "project:create",
  create_template: "template:create",
  create_environment: "environment:create",
  deploy_resource: "resource:update",
  deploy_template: "template:deploy",
  control_resource: "resource:update",
  delete_resource: "resource:delete",
  delete_project: "project:delete",
  prune_docker_resources: "server:update",
  exec_container_command: "server:update",
  exec_server_terminal_command: "server:update",
  get_project: "project:view",
  get_environment: "environment:view",
  get_resource: "resource:view",
  get_resource_containers: "resource:view",
  get_resource_previews: "resource:view",
  get_resource_routing_targets: "resource:view",
  list_resource_backup_schedules: "backup:view",
  list_resource_backup_runs: "backup:view",
  list_backup_volumes: "backup:view",
  list_git_providers: "git_provider:view",
  list_docker_registries: "docker_registry:view",
  search_upstand: "project:view",
  get_swarm_info: "swarm:view",
  get_swarm_nodes: "swarm:view",
  get_swarm_containers: "swarm:view",
  get_web_server_logs: "server:view",
  get_update_status: "server:view",
  list_tags: "tag:view",
  get_resource_tags: "tag:view",
  create_tag: "tag:create",
  update_tag: "tag:update",
  delete_tag: "tag:delete",
  assign_resource_tag: "tag:update",
  detach_resource_tag: "tag:update",
  list_schedules: "resource:view",
  create_schedule: "resource:update",
  update_schedule: "resource:update",
  delete_schedule: "resource:update",
  trigger_schedule: "resource:update",
  search_web: "ai:view",
  guide_upstand: "ai:view",
} as const satisfies Record<string, Capability>;

export const MCP_READ_ONLY_TOOL_NAMES = [
  "get_account_status",
  "list_templates",
  "get_template",
  "list_projects",
  "list_environments",
  "list_resources",
  "get_resource_logs",
  "get_resource_stats",
  "get_resource_config",
  "list_servers",
  "get_monitoring_status",
  "get_monitoring_metrics",
  "list_deployments",
  "get_audit_logs",
  "get_docker_info",
  "list_docker_containers",
  "list_docker_images",
  "list_docker_volumes",
  "list_docker_networks",
  "list_docker_services",
  "get_docker_logs",
  "get_project",
  "get_environment",
  "get_resource",
  "get_resource_containers",
  "get_resource_previews",
  "get_resource_routing_targets",
  "list_resource_backup_schedules",
  "list_resource_backup_runs",
  "list_backup_volumes",
  "list_git_providers",
  "list_docker_registries",
  "search_upstand",
  "get_swarm_info",
  "get_swarm_nodes",
  "get_swarm_containers",
  "get_web_server_logs",
  "get_update_status",
  "list_tags",
  "get_resource_tags",
  "list_schedules",
  "search_web",
  "guide_upstand",
] as const satisfies readonly (keyof typeof MCP_TOOL_CAPABILITIES)[];
