import type { IAuditLogRepository } from "./audit-log-repository.interface";
import type { IBackupRunRepository } from "./backup-run-repository.interface";
import type { IBackupScheduleRepository } from "./backup-schedule-repository.interface";
import type { ICertificateRepository } from "./certificate-repository.interface";
import type { IDeploymentRepository } from "./deployment-repository.interface";
import type { IDockerRegistryRepository } from "./docker-registry-repository.interface";
import type { IEnvironmentRepository } from "./environment-repository.interface";
import type { IGitProviderRepository } from "./git-provider-repository.interface";
import type { IMonitoringSettingsRepository } from "./monitoring-settings-repository.interface";
import type { INotificationChannelRepository } from "./notification-channel-repository.interface";
import type { INotificationDeliveryRepository } from "./notification-delivery-repository.interface";
import type { IOutboxRepository } from "./outbox-repository.interface";
import type { IPreviewDeploymentRepository } from "./preview-deployment-repository.interface";
import type { IProjectRepository } from "./project-repository.interface";
import type { IResourceRepository } from "./resource-repository.interface";
import type { IResourceRuntimeRepository } from "./resource-runtime-repository.interface";
import type { IS3DestinationRepository } from "./s3-destination-repository.interface";
import type { IScheduleLogRepository } from "./schedule-log-repository.interface";
import type { IScheduleRepository } from "./schedule-repository.interface";
import type { IServerBuildSettingsRepository } from "./server-build-settings-repository.interface";
import type { IServerRepository } from "./server-repository.interface";
import type { ISshKeyRepository } from "./ssh-key-repository.interface";
import type { ITagRepository } from "./tag-repository.interface";
import type { ITemplateRepository } from "./template-repository.interface";
import type { IUserRepository } from "./user-repository.interface";
import type { IWebServerSettingsRepository } from "./web-server-settings-repository.interface";

export interface IUnitOfWork {
  readonly auditLogRepository: IAuditLogRepository;
  readonly backupScheduleRepository: IBackupScheduleRepository;
  readonly certificateRepository: ICertificateRepository;
  readonly backupRunRepository: IBackupRunRepository;
  readonly userRepository: IUserRepository;
  readonly projectRepository: IProjectRepository;
  readonly tagRepository: ITagRepository;
  readonly templateRepository: ITemplateRepository;
  readonly environmentRepository: IEnvironmentRepository;
  readonly resourceRepository: IResourceRepository;
  readonly resourceRuntimeRepository: IResourceRuntimeRepository;
  readonly sshKeyRepository: ISshKeyRepository;
  readonly gitProviderRepository: IGitProviderRepository;
  readonly webServerSettingsRepository: IWebServerSettingsRepository;
  readonly s3DestinationRepository: IS3DestinationRepository;
  readonly serverBuildSettingsRepository: IServerBuildSettingsRepository;
  readonly deploymentRepository: IDeploymentRepository;
  readonly dockerRegistryRepository: IDockerRegistryRepository;
  readonly serverRepository: IServerRepository;
  readonly notificationChannelRepository: INotificationChannelRepository;
  readonly notificationDeliveryRepository: INotificationDeliveryRepository;
  readonly monitoringSettingsRepository: IMonitoringSettingsRepository;
  readonly previewDeploymentRepository: IPreviewDeploymentRepository;
  readonly scheduleRepository: IScheduleRepository;
  readonly scheduleLogRepository: IScheduleLogRepository;
  readonly outboxRepository: IOutboxRepository;
  transaction<T>(work: (uow: IUnitOfWork) => Promise<T>): Promise<T>;
}
